### ISSUE TITLE
Display date

### ISSUE THREAD

**Issue by piever** [budparr/gohugo-theme-ananke#85] opened 2018-02-23 14:25 UTC
Thanks for developing the theme, I find it very nice and functional.

I only have one small gripe: the them does not display the dates of blog posts. In the [demo](https://gohugo-ananke-theme-demo.netlify.com/) there seems to be the same issue: even though the markdown files have the date information, it is not displayed.

Is there some setting I can tweak to show the date on the blog posts?

**Comment by budparr** [comment] 2018-02-23 15:05
Hi @piever Do you mean aside from these places?

<img width="423" alt="screen shot 2018-02-23 at 10 05 00 am" src="https://user-images.githubusercontent.com/115347/36600720-0f6361d0-1881-11e8-8689-415a107f7410.png">
<img width="289" alt="screen shot 2018-02-23 at 10 04 52 am" src="https://user-images.githubusercontent.com/115347/36600721-0f74eb26-1881-11e8-8be3-8dd0907e2e73.png">

**Comment by piever** [comment] 2018-02-23 16:45
Ups, hadn't noticed it there. Then I must be doing something wrong, as I can't visualize it in my blog, but the beginning of my markdown file has a date. [Here](https://piever.github.io/simpleblog/posts/juliadb/) is a sample post (date doesn't show) and [here](https://github.com/piever/simpleblog/blob/master/content/posts/juliaDB.md) is the corresponding markdown. I'm on the latest commit of this theme and on latest hugo release.

I somehow assumed it was an ananke issue as by googling it seemd other people had it. See for example the comment immediately above the linked [header](https://code.luasoftware.com/tutorials/hugo/how-to-use-hugo/#deployment):

> Ananke Theme issues
> 
> You might have notice the post is displayed without a date, this issue is related to the Ananke theme.

**Comment by budparr** [comment] 2018-02-23 16:53
Can you point me to your repo?

**Comment by piever** [comment] 2018-02-23 16:57
Thanks a lot! Here is the repo:

https://github.com/piever/simpleblog

**Comment by budparr** [comment] 2018-02-23 17:13
Hey, @piever so it's not a bug. The date is set for posts, but not for other article types, which means any entries in the `post` directory (it's generally suggested to use singular folder names in content) will have a date, and others will not.

I will consider some way to make that more flexible (i've begun work on updating the theme), but in the meantime, you can either copy `themes/ananke/layouts/_default/single.html` into your root layout folder (so, `layouts/_default/single.html`) and add the date there ([reference](https://github.com/budparr/gohugo-theme-ananke/blob/master/layouts/post/single.html#L18)), or change your content's `posts` folder to `post.`

I'm closing this and, if you wish to follow the issue, it's referenced here on the page.

**Closed by budparr** 2018-02-23 17:13 UTC

**Comment by piever** [comment] 2018-02-23 20:53
Wow, removing the "s" folder from the `posts` folder (it's now called `post`) fixed it, thanks a lot!

Not sure if there's any need to change this, but it's probably worth a mention in the README as the result of googling "ananke hugo date not displayed" was [this tutorial](https://code.luasoftware.com/tutorials/hugo/how-to-use-hugo/#deployment) where the put posts in the `posts` folder and then say: "date does not display, it's an issue with the theme"...

**Comment by budparr** [comment] 2018-02-23 21:00
Good idea, thanks. And had that person bothered to dig a little deeper, as you did, before claiming the theme was just bad in a public forum, we'd all be better off.
